;;; package --- iterati-theme.el
;;; Commentary:
;;; Code:
(require 'doom-themes)

(defvar modeline-bg)

(defgroup iterati-theme nil
  "Options for iterati."
  :group 'doom-themes)

(defcustom iterati-light nil
  "If non-nil, will use the light mode."
  :group 'iterati-theme
  :type 'boolean)

(def-doom-theme iterati
  "Gruvbox colors, iterati composition."
  ((bg           (if iterati-light '("#f9f5d7" nil nil) '("#1d2021" nil nil)))
   (bg-alt       (if iterati-light '("#f2e5bc" nil nil) '("#32302f" nil nil)))
   (base0        (if iterati-light '("#fbf1c7" nil nil) '("#282828" nil nil)))
   (base1        (if iterati-light '("#ebdbb2" nil nil) '("#3c3836" nil nil)))
   (base2        (if iterati-light '("#d5c4a1" nil nil) '("#504945" nil nil)))
   (base3        (if iterati-light '("#bdae93" nil nil) '("#665c54" nil nil)))
   (base4        (if iterati-light '("#a89984" nil nil) '("#7c6f64" nil nil)))
   (base5        (if iterati-light '("#928374" nil nil) '("#928374" nil nil)))
   (base6        (if iterati-light '("#7c6f64" nil nil) '("#a89984" nil nil)))
   (base7        (if iterati-light '("#665c54" nil nil) '("#bdae93" nil nil)))
   (base8        (if iterati-light '("#282828" nil nil) '("#fbf1c7" nil nil)))
   (fg           (if iterati-light '("#3c3836" nil nil) '("#ebdbb2" nil nil)))
   (fg-alt       (if iterati-light '("#504945" nil nil) '("#d5c4a1" nil nil)))
   (red          (if iterati-light '("#9d0006" nil nil) '("#fb4934" nil nil)))
   (orange       (if iterati-light '("#af3a03" nil nil) '("#fe8019" nil nil)))
   (yellow       (if iterati-light '("#b57614" nil nil) '("#fabd2f" nil nil)))
   (green        (if iterati-light '("#79740e" nil nil) '("#b8bb26" nil nil)))
   (cyan         (if iterati-light '("#427b58" nil nil) '("#8ec07c" nil nil)))
   (blue         (if iterati-light '("#076678" nil nil) '("#83a598" nil nil)))
   (magenta      (if iterati-light '("#8f3f71" nil nil) '("#d3869b" nil nil)))
   (dark-red     '("#cc241d" nil nil))
   (dark-orange  '("#d65d0e" nil nil))
   (dark-yellow  '("#d79921" nil nil))
   (dark-green   '("#98971a" nil nil))
   (dark-cyan    '("#689d6a" nil nil))
   (dark-blue    '("#458588" nil nil))
   (dark-magenta '("#b16286" nil nil))
   (grey         base5)
   (violet       dark-red)
   (teal         dark-magenta)

   (w1 'thin)       ;; for comments/inactive things
   (w2 'extralight) ;; base-line emphasis/normal things
   (w3 'normal)     ;; some emphasis/language syntax
   (w4 'semibold)   ;; strongest emphasis/highlight, selection, and search

   (success      green)
   (warning      yellow)
   (error        red)
   (vc-added     dark-green)
   (vc-modified  dark-yellow)
   (vc-deleted   dark-red)
   (vertical-bar bg-alt)
   (highlight    base2)
   (selection    highlight)
   (region       highlight)
   (comments     grey)
   (doc-comments base7)
   (operators    red)
   (keywords     orange)
   (methods      yellow)
   (type         green)
   (variables    cyan)
   (strings      blue)
   (constants    magenta)
   ;; dark-red
   (builtin      dark-yellow)
   ;; dark-orange - html tags
   ;; dark-green - html attrs
   (functions    dark-cyan)
   (numbers      dark-blue)
   ;; dark-magenta
   )

  (;; ui elements
   ((default &override)                                                                       :weight w2)
   ((region &override)                                                                        :weight w4)
   (auto-dim-other-buffers-face             :background bg-alt)
   (fringe                                  :background bg-alt       :foreground grey)
   (window-divider                                                   :foreground bg-alt)
   (line-number                             :background bg-alt       :foreground grey         :weight w1)
   (line-number-current-line                :background bg-alt       :foreground fg-alt       :weight w4)
   (hl-line                                 :background bg-alt                                :weight w4)
   (mode-line                               :background bg           :foreground fg-alt       :weight w2 :box bg-alt)
   (mode-line-inactive                      :background bg-alt       :foreground grey         :weight w1 :box bg-alt)
   (mode-line-emphasis                      :background bg-alt       :foreground fg-alt)
   (mode-line-highlight                     :background bg-alt       :foreground fg-alt)
   (doom-modeline-project-dir                                        :foreground fg-alt       :weight w3 :slant 'italic)
   (doom-modeline-buffer-path                                        :foreground fg-alt       :weight w2 :slant 'italic)
   (doom-modeline-buffer-file                                        :foreground fg-alt       :weight w4 :slant 'italic)
   (doom-modeline-buffer-major-mode                                  :foreground fg-alt)
   (doom-modeline-info                                               :foreground fg-alt)
   (doom-modeline-debug                                              :foreground grey)
   (doom-modeline-warning                                            :foreground yellow)
   (doom-modeline-urgent                                             :foreground red)
   (doom-modeline-evil-normal-state                                  :foreground green)
   (company-tooltip                         :background bg           :foreground fg-alt)
   (company-tooltip-common                  :background bg-alt                                :weight w4)
   (company-tooltip-selection               :background highlight                             :weight w4)
   (company-tooltip-mouse                   :background magenta      :foreground bg-alt       :weight w4)
   (treemacs-root-face                                               :foreground fg           :weight w4)
   (treemacs-directory-face                                          :foreground fg           :weight w3)
   (treemacs-file-face                                               :foreground fg           :weight w2)
   ;; syntax highlighting
   ((font-lock-comment-delimiter-face &override)                                              :weight w1)
   ((font-lock-comment-face &override)                                                        :weight w1 :slant 'italic)
   ((font-lock-doc-face &override)                                                            :weight w1 :slant 'italic)
   ((highlight-numbers-number &override)                                                      :weight w3)
   ((font-lock-keyword-face &override)                                                        :weight w3)
   ((font-lock-function-name-face &override)                                                  :weight w3)
   ((font-lock-type-face &override)                                                           :weight w3)
   ((font-lock-constant-face &override)                                                       :weight w3)
   ((font-lock-string-face &override)                                                         :weight w3)
   ((font-lock-builtin-face &override)                                                        :weight w3)
   ((web-mode-keyword-face &override)                                                         :weight w3)
   (web-mode-html-attr-name-face                                     :foreground dark-green   :weight w3)
   (web-mode-html-tag-bracket-face                                   :foreground dark-orange  :weight w3)
   (web-mode-html-tag-face                                           :foreground dark-orange  :weight w3)
   (web-mode-current-element-highlight-face :background highlight                             :weight w4)
   (lsp-face-highlight-textual              :background highlight                             :weight w4)
   (rainbow-delimiters-depth-1-face                                  :foreground red          :weight w3)
   (rainbow-delimiters-depth-2-face                                  :foreground orange       :weight w3)
   (rainbow-delimiters-depth-3-face                                  :foreground yellow       :weight w3)
   (rainbow-delimiters-depth-4-face                                  :foreground green        :weight w3)
   (rainbow-delimiters-depth-5-face                                  :foreground cyan         :weight w3)
   (rainbow-delimiters-depth-6-face                                  :foreground blue         :weight w3)
   (rainbow-delimiters-depth-7-face                                  :foreground magenta      :weight w3)
   (lazy-highlight                          :background highlight                             :weight w4 :slant 'italic)
   (evil-ex-search                          :background highlight                             :weight w4 :slant 'italic)
   (show-paren-match                        :background highlight                             :weight w4 :slant 'italic)
   (orderless-match-face-0                  :background dark-yellow  :foreground bg           :weight w4)
   (orderless-match-face-1                  :background dark-orange  :foreground bg           :weight w4)
   (orderless-match-face-2                  :background dark-red     :foreground bg           :weight w4)
   (orderless-match-face-3                  :background dark-magenta :foreground bg           :weight w4)
   ;; magit stuff
   (magit-header-line                       :background bg-alt       :foreground fg)
   (magit-diff-our                          :background highlight    :foreground dark-red)
   (magit-diff-our-highlight                :background highlight    :foreground dark-red)
   (magit-diff-context                      :background bg-alt       :foreground grey)
   (magit-diff-context-highlight            :background bg           :foreground grey)
   (magit-diff-added                        :background bg-alt       :foreground dark-green)
   (magit-diff-added-highlight              :background bg           :foreground dark-green)
   (magit-diff-their                        :background bg-alt       :foreground dark-green)
   (magit-diff-their-highlight              :background bg           :foreground dark-green)
   (magit-diff-base                         :background bg-alt       :foreground dark-orange)
   (magit-diff-base-highlight               :background bg           :foreground dark-orange)
   (magit-diff-removed                      :background bg-alt       :foreground red)
   (magit-diff-removed-highlight            :background bg           :foreground red)
   (magit-diff-file-heading                 :background bg-alt       :foreground fg           :weight w3)
   (magit-diff-file-heading-highlight       :background bg           :foreground fg           :weight w3)
   (magit-diff-file-heading-selection       :background highlight    :foreground fg           :weight w3)
   (magit-diff-hunk-heading                 :background bg-alt       :foreground fg-alt       :weight w3)
   (magit-diff-hunk-heading-highlight       :background bg           :foreground fg-alt       :weight w3)
   (magit-diff-hunk-heading-selection       :background highlight    :foreground fg-alt       :weight w3)
   (magit-diff-lines-heading                :background bg-alt       :foreground dark-yellow  :weight w3)
   (magit-diff-lines-boundary               :background bg-alt       :foreground dark-yellow  :weight w3)
   (magit-diff-conflict-heading             :background dark-red     :foreground fg-alt)
   (magit-diff-revision-summary             :background dark-red     :foreground fg-alt)
   (magit-diff-revision-summary-highlight   :background dark-red     :foreground fg-alt)
   (magit-diff-whitespace-warning           :background red          :foreground fg-alt)
   (magit-blame-margin                      :background bg-alt       :foreground fg-alt)
   (magit-blame-heading                     :background bg-alt       :foreground fg)
   (magit-blame-summary                     :background bg-alt       :foreground fg-alt)
   (magit-blame-highlight                   :background highlight    :foreground fg-alt)
   (magit-branch-remote-head                :background base0        :foreground green)
   (diff-refine-added                       :background dark-green   :foreground bg)
   (diff-refine-changed                     :background dark-yellow  :foreground bg)
   (diff-refine-removed                     :background dark-red     :foreground bg)
   (diff-removed                            :background bg           :foreground dark-red)))

(provide 'iterati-theme)
;;; iterati-theme.el ends here
